#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LITDucks.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LITDucks")]
	public partial class LITDucksDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQuackCount(QuackCount instance);
    partial void UpdateQuackCount(QuackCount instance);
    partial void DeleteQuackCount(QuackCount instance);
    #endregion
		
		public LITDucksDataContext() : 
				base(global::LITDucks.Data.Properties.Settings.Default.LITDucksConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LITDucksDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LITDucksDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LITDucksDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LITDucksDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<QuackCount> QuackCounts
		{
			get
			{
				return this.GetTable<QuackCount>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuackCounts")]
	public partial class QuackCount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _RealDuckCount;
		
		private int _RubberDuckCount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRealDuckCountChanging(int value);
    partial void OnRealDuckCountChanged();
    partial void OnRubberDuckCountChanging(int value);
    partial void OnRubberDuckCountChanged();
    #endregion
		
		public QuackCount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealDuckCount", DbType="Int NOT NULL")]
		public int RealDuckCount
		{
			get
			{
				return this._RealDuckCount;
			}
			set
			{
				if ((this._RealDuckCount != value))
				{
					this.OnRealDuckCountChanging(value);
					this.SendPropertyChanging();
					this._RealDuckCount = value;
					this.SendPropertyChanged("RealDuckCount");
					this.OnRealDuckCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RubberDuckCount", DbType="Int NOT NULL")]
		public int RubberDuckCount
		{
			get
			{
				return this._RubberDuckCount;
			}
			set
			{
				if ((this._RubberDuckCount != value))
				{
					this.OnRubberDuckCountChanging(value);
					this.SendPropertyChanging();
					this._RubberDuckCount = value;
					this.SendPropertyChanged("RubberDuckCount");
					this.OnRubberDuckCountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
